# -*- coding: utf-8 -*-
"""Enumerating k-mers Lexicographically.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LaxYQThTqIceAkEDjFxt54Zbrb3uS4kl
"""

import os
os.chdir('c:/Users/mjmah/OneDrive/Desktop/everything/Main/term7/bio/HWs/HW1/q4')

chars = None
number = -1
with open('rosalind_lexf.txt', 'r') as file:
  inputs = []
  for line in file:
    inputs.append(line.split())
  chars = inputs[0]
  chars.sort()
  number = inputs[1][0]


def find_all(depth, current_string):
  if depth == 0:
    print(current_string)
    return
  for char in chars:
    find_all(depth-1, current_string + char)

find_all(int(number), "")

