# -*- coding: utf-8 -*-
"""DNA to RNA Convertion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U2L6QalGGxqyCeGmlqNCgPApKhcS6CeK
"""

import os
os.chdir('c:/Users/mjmah/OneDrive/Desktop/everything/Main/term7/bio/HWs/HW1/q3')

with open('rosalind_rna.txt', 'r') as file:
    for line in file:
      string = line
    final = ""
    for char in string:
      if char == 'T':
        final += 'U'
      else:
        final += char
    print(final)